# Generated by Django 3.1.6 on 2021-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragndrop', '0002_auto_20210204_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='transcriptionShort',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
