# Generated by Django 3.1.6 on 2021-02-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragndrop', '0003_audiorecord_transcriptionshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='hashCode',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
