# Generated by Django 3.1.6 on 2021-02-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragndrop', '0004_audiorecord_hashcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='actualFileName',
            field=models.CharField(default='', max_length=68),
            preserve_default=False,
        ),
    ]
