# Generated by Django 3.1.6 on 2021-02-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragndrop', '0005_audiorecord_actualfilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecord',
            name='transcription',
        ),
    ]
