# Generated by Django 3.1.6 on 2021-02-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragndrop', '0007_audiorecord_transcriptionfilename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecord',
            old_name='transcriptionFileName',
            new_name='actualTranscriptionFileName',
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='audioFileName',
            field=models.CharField(max_length=259),
        ),
    ]
