# Generated by Django 3.1.6 on 2021-02-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragndrop', '0008_auto_20210205_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='keyWords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
