# Generated by Django 3.1.6 on 2021-02-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragndrop', '0009_audiorecord_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='actualWordCloudFileName',
            field=models.CharField(default='', max_length=68),
            preserve_default=False,
        ),
    ]
